# Generated by Django 5.2.2 on 2025-07-02 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PanierModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du client propriétaire"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "panier_paniers",
                "ordering": ["-date_modification"],
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="panier_pani_client__1f78ca_idx"
                    ),
                    models.Index(
                        fields=["date_creation"], name="panier_pani_date_cr_23022a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProduitPanierModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "produit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID du produit depuis le service-catalogue",
                    ),
                ),
                (
                    "nom_produit",
                    models.CharField(
                        help_text="Nom du produit (dénormalisé pour performance)",
                        max_length=255,
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de l'ajout au panier",
                        max_digits=10,
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        help_text="Quantité de ce produit dans le panier"
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "panier",
                    models.ForeignKey(
                        help_text="Panier contenant ce produit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="panier.paniermodel",
                    ),
                ),
            ],
            options={
                "db_table": "panier_produits",
                "indexes": [
                    models.Index(
                        fields=["produit_id"], name="panier_prod_produit_71382a_idx"
                    ),
                    models.Index(
                        fields=["panier", "produit_id"],
                        name="panier_prod_panier__f52e00_idx",
                    ),
                ],
                "unique_together": {("panier", "produit_id")},
            },
        ),
    ]
