# Generated by Django 5.2.2 on 2025-07-02 18:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prenom",
                    models.CharField(help_text="Prénom du client", max_length=100),
                ),
                ("nom", models.CharField(help_text="Nom du client", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email unique du client",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("adresse_rue", models.TextField(help_text="Adresse rue")),
                ("adresse_ville", models.CharField(help_text="Ville", max_length=100)),
                (
                    "adresse_code_postal",
                    models.CharField(help_text="Code postal", max_length=10),
                ),
                (
                    "adresse_province",
                    models.CharField(
                        default="Québec", help_text="Province", max_length=50
                    ),
                ),
                (
                    "adresse_pays",
                    models.CharField(default="Canada", help_text="Pays", max_length=50),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "actif",
                    models.BooleanField(default=True, help_text="Compte actif ou non"),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["-date_creation"],
            },
        ),
    ]
