# Generated by Django 4.2.7 on 2025-06-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='active', max_length=20),
        ),
    ]
