# Generated by Django 5.2.2 on 2025-07-02 19:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessusCheckoutModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(db_index=True, help_text="UUID du client"),
                ),
                (
                    "panier_id",
                    models.UUIDField(db_index=True, help_text="UUID du panier"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("initialise", "Initialisé"),
                            ("panier_valide", "Panier Validé"),
                            ("adresse_definie", "Adresse Définie"),
                            ("stocks_valides", "Stocks Validés"),
                            ("finalise", "Finalisé"),
                            ("echec", "Échec"),
                        ],
                        default="initialise",
                        help_text="Statut actuel du processus de check-out",
                        max_length=20,
                    ),
                ),
                (
                    "sous_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sous-total des produits",
                        max_digits=10,
                    ),
                ),
                (
                    "frais_livraison",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Frais de livraison",
                        max_digits=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de la commande",
                        max_digits=10,
                    ),
                ),
                (
                    "adresse_nom_destinataire",
                    models.CharField(help_text="Nom du destinataire", max_length=200),
                ),
                ("adresse_rue", models.TextField(help_text="Adresse rue")),
                ("adresse_ville", models.CharField(help_text="Ville", max_length=100)),
                (
                    "adresse_code_postal",
                    models.CharField(help_text="Code postal", max_length=20),
                ),
                (
                    "adresse_province",
                    models.CharField(help_text="Province", max_length=50),
                ),
                (
                    "adresse_pays",
                    models.CharField(default="Canada", help_text="Pays", max_length=50),
                ),
                (
                    "adresse_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions de livraison", null=True
                    ),
                ),
                (
                    "livraison_express",
                    models.BooleanField(default=False, help_text="Livraison express"),
                ),
                (
                    "commande_externe_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID de la commande créée dans le service-commandes",
                        null=True,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_finalisation", models.DateTimeField(blank=True, null=True)),
                (
                    "erreurs",
                    models.JSONField(
                        default=list, help_text="Liste des erreurs rencontrées"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes additionnelles", null=True
                    ),
                ),
            ],
            options={
                "db_table": "commandes_processus_checkout",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["client_id"], name="commandes_p_client__ba7592_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="commandes_p_statut_ff6d99_idx"
                    ),
                    models.Index(
                        fields=["date_creation"], name="commandes_p_date_cr_b90a10_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneCheckoutModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "produit_id",
                    models.UUIDField(db_index=True, help_text="UUID du produit"),
                ),
                (
                    "nom_produit",
                    models.CharField(help_text="Nom du produit", max_length=255),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(help_text="Quantité commandée"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment du check-out",
                        max_digits=10,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "processus_checkout",
                    models.ForeignKey(
                        help_text="Processus de check-out parent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="commandes.processuscheckoutmodel",
                    ),
                ),
            ],
            options={
                "db_table": "commandes_lignes_checkout",
                "indexes": [
                    models.Index(
                        fields=["produit_id"], name="commandes_l_produit_3fcc3c_idx"
                    ),
                    models.Index(
                        fields=["processus_checkout", "produit_id"],
                        name="commandes_l_process_87989b_idx",
                    ),
                ],
                "unique_together": {("processus_checkout", "produit_id")},
            },
        ),
    ]
