# Generated by Django 5.2.2 on 2025-07-02 21:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeEcommerce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_id", models.UUIDField(db_index=True)),
                ("checkout_id", models.UUIDField(unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("payee", "Payée"),
                            ("expediee", "Expédiée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="validee",
                        max_length=20,
                    ),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("sous_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frais_livraison",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nom_destinataire", models.CharField(max_length=255)),
                ("rue", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=100)),
                ("code_postal", models.CharField(max_length=20)),
                ("province", models.CharField(max_length=50)),
                ("pays", models.CharField(default="Canada", max_length=50)),
                ("instructions_livraison", models.TextField(blank=True, null=True)),
                ("livraison_express", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("nombre_articles", models.PositiveIntegerField()),
                ("nombre_produits", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "ecommerce_commandes",
                "ordering": ["-date_commande"],
                "indexes": [
                    models.Index(
                        fields=["client_id", "-date_commande"],
                        name="ecommerce_c_client__fec618_idx",
                    ),
                    models.Index(
                        fields=["statut"], name="ecommerce_c_statut_d0add4_idx"
                    ),
                    models.Index(
                        fields=["date_commande"], name="ecommerce_c_date_co_15b5fa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LigneCommandeEcommerce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("produit_id", models.UUIDField()),
                ("nom_produit", models.CharField(max_length=255)),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="commandes.commandeecommerce",
                    ),
                ),
            ],
            options={
                "db_table": "ecommerce_lignes_commandes",
                "indexes": [
                    models.Index(
                        fields=["commande"], name="ecommerce_l_command_508f7a_idx"
                    ),
                    models.Index(
                        fields=["produit_id"], name="ecommerce_l_produit_767b22_idx"
                    ),
                ],
            },
        ),
    ]
