# Generated by Django 5.2.2 on 2025-06-28 19:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeReapprovisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_id', models.UUIDField()),
                ('magasin_id', models.UUIDField()),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockCentral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_id', models.UUIDField()),
                ('quantite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produit_id', models.UUIDField()),
                ('magasin_id', models.UUIDField()),
                ('quantite', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
