# Generated by Django 4.2.7 on 2025-06-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='quantite_stock',
        ),
    ]
